# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Atalasoft Dev Team Blog
tagline:
description:         'Technical blog based on wisdom <a href="https://atalasoft.com" target="_blank">Atalasoft</a> Dev Team gathered and wants to share :)'
url:                 http://atalasoft.github.io
baseurl:             ''
paginate:            5

pages_list:
  Archive: '/archive'
  Tags: '/tags'
  About: '/about'
  Feed: '/atom.xml'

# About/contact
author:
  name:              Atalasoft from Lexmark
  url:               https://twitter.com/atalasoft

github:
  repo:           https://github.com/atalasoft/atalasoft.github.io

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
